// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Deterministic decision whether Klacksy asks an employee back about an unclear inbound message
/// (Ask), only suggests the question to the planners (Suggest) or stays on the regular path (Skip).
/// No IO: every fact is gathered by the caller. The order of the checks is part of the contract: hard
/// exclusions first (no need, not an employee, not planning relevant, switch off, auto-generated mail,
/// open clarification, rate limit), then the release gate (kill switch active or global autonomy level
/// below Assisted means Suggest, so nothing goes out), and only then the personal contact, so a
/// suggestion reaches the planners even when the employee has no personal contact on the channel.
/// </summary>
/// <param name="facts">Everything the decision depends on, gathered by ClarificationCoordinator</param>

using Klacks.Api.Domain.Constants;
using Klacks.Api.Domain.Enums;
using Klacks.Api.Domain.Models.Inbound;

namespace Klacks.Api.Domain.Services.Inbound;

public static class ClarificationPolicy
{
    public static ClarificationDecision Decide(ClarificationPolicyFacts facts)
    {
        if (!facts.NeedsClarification)
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.NotNeeded);
        }

        if (facts.ClientType is not (EntityTypeEnum.Employee or EntityTypeEnum.ExternEmp))
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.NotEmployee);
        }

        if (!IsPlanningRelevant(facts.Intent))
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.NotPlanningRelevant);
        }

        if (!facts.FeatureEnabled)
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.FeatureDisabled);
        }

        if (facts.IsAutoGenerated)
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.AutoGeneratedEmail);
        }

        if (facts.HasOpenClarification)
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.OpenClarificationExists);
        }

        if (facts.QuestionsAskedInRateWindow >= InboundClarificationConstants.MaxQuestionsPerRateLimitWindow)
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.RateLimited);
        }

        if (facts.KillSwitchActive || facts.GlobalAutonomyLevel < AutonomyLevel.Assisted)
        {
            return ClarificationDecision.Suggest;
        }

        if (!facts.HasPersonalReplyTarget)
        {
            return ClarificationDecision.Skip(ClarificationSkipReason.NoPersonalReplyTarget);
        }

        return ClarificationDecision.Ask;
    }

    private static bool IsPlanningRelevant(EmailIntent intent) => intent is
        EmailIntent.WorkCancellation or
        EmailIntent.VacationRequest or
        EmailIntent.DayOffWish or
        EmailIntent.AvailabilityAnnouncement or
        EmailIntent.ShiftPreference or
        EmailIntent.Other;
}
