// <auto-generated />
using System;
using Klacks.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Klacks.Api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20250827000000_AddPasswordResetTokenFields")]
    partial class AddPasswordResetTokenFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a simplified version - in a real scenario you'd need the full model
            // For now, we'll just note that this migration adds password reset fields to AppUser
        }
    }
}