// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Repository registrations, split out of ServiceCollectionExtensions so that file stays under its
/// size-guard ceiling. The registration lines, their lifetimes and their order are unchanged, and
/// AddApplicationServices still calls this at the position it always occupied.
/// </summary>
using System.Runtime.InteropServices;
using Klacks.Api.Application.Interfaces;
using Klacks.Api.Application.Services;
using Klacks.Api.Application.Skills;
using Klacks.Api.Infrastructure.Scripting;
using Klacks.Api.Domain.Interfaces;
using Klacks.Api.Domain.Interfaces.Assistant;
using Klacks.Api.Domain.Interfaces.Authentification;
using Klacks.Api.Domain.Interfaces.RouteOptimization;
using Klacks.Api.Domain.Interfaces.Settings;
using Klacks.Api.Domain.Interfaces.Staffs;
using Klacks.Api.Infrastructure.Repositories.Assistant;
using Klacks.Api.Domain.Services.Absences;
using Klacks.Api.Domain.Services.Accounts;
using Klacks.Api.Infrastructure.Services.CalendarSelections;
using Klacks.Api.Domain.Services.Clients;
using Klacks.Api.Infrastructure.Services.Clients;
using Klacks.Api.Domain.Services.ContainerTemplates;
using Klacks.Api.Domain.Services.Groups;
using Klacks.Api.Domain.Services.Holidays;
using Klacks.Api.Domain.Services.Settings;
using Klacks.Api.Domain.Services.Shifts;
using Klacks.Api.Application.Common;
using Klacks.Api.Domain.Services.ShiftSchedule;
using Klacks.Api.Infrastructure.Services.ShiftSchedule;
using Klacks.Api.Infrastructure.Services.ScheduleEntries;
using Klacks.Api.Infrastructure.Services.AnalyseScenarios;
using Klacks.Api.Infrastructure.Services.PeriodHours;
using Klacks.Api.Domain.Services.Assistant;
using Klacks.Api.Infrastructure.Services.Assistant;
using Klacks.Api.Application.Services.Assistant;
using Klacks.Api.Domain.Services.Assistant.Skills;
using Klacks.Api.Domain.Services.RouteOptimization;
using Klacks.Api.Domain.Services.Common;
using Klacks.Api.Infrastructure.Services.Macros;
using Klacks.Api.Domain.Services.Schedules;
using Klacks.Api.Infrastructure.Services.Schedules;
using Klacks.Api.Domain.Interfaces.Email;
using Klacks.Api.Infrastructure.Email;
using Klacks.Api.Infrastructure.FileHandling;
using Klacks.Api.Infrastructure.Interfaces;
using Klacks.Api.Infrastructure.Persistence;
using Klacks.Api.Infrastructure.Repositories;
using Klacks.Api.Infrastructure.Repositories.Associations;
using Klacks.Api.Infrastructure.Repositories.Email;
using Klacks.Api.Infrastructure.Repositories.Authentification;
using Klacks.Api.Infrastructure.Repositories.CalendarSelections;
using Klacks.Api.Infrastructure.Repositories.Imports;
using Klacks.Api.Infrastructure.Repositories.Reports;
using Klacks.Api.Infrastructure.Repositories.Schedules;
using Klacks.Api.Infrastructure.Repositories.Scheduling;
using Klacks.Api.Infrastructure.Repositories.Settings;
using Klacks.Api.Infrastructure.Repositories.Exports;
using Klacks.Api.Infrastructure.Repositories.Staffs;
using Klacks.Api.Infrastructure.Services;
using Klacks.Api.Infrastructure.Services.Groups;
using Klacks.Api.Infrastructure.Services.Settings;
using Klacks.Api.Infrastructure.Services.Shifts;
using Klacks.Api.Application.Services.Authentication;
using Klacks.Api.Application.Services.Clients;
using Klacks.Api.Application.Services.Identity;
using Klacks.Api.Application.Services.Schedules;
using Klacks.Api.Application.Interfaces.Schedules;
using Klacks.Api.Application.Services.Translation;
using Klacks.Api.Domain.Interfaces.Associations;
using Klacks.Api.Domain.Interfaces.Schedules;
using Klacks.Api.Application.Interfaces.Plugins;
using Klacks.Api.Application.Interfaces.Settings;
using Klacks.Api.Infrastructure.Services.Associations;
using Klacks.Api.Infrastructure.Services.Plugins;
using Klacks.Api.Infrastructure.Services.ClientAvailabilitySchedule;
using Klacks.Api.Application.Configuration;
using Klacks.Api.Application.Skills.Generated;
using Klacks.Api.Application.Skills.Generic;
using Klacks.Api.KnowledgeIndex.Application.Constants;
using Klacks.Api.KnowledgeIndex.Application.Interfaces;
using Klacks.Api.KnowledgeIndex.Application.Services;
using Klacks.Api.KnowledgeIndex.Infrastructure.Api;
using Klacks.Api.KnowledgeIndex.Infrastructure.Onnx;
using Klacks.Api.KnowledgeIndex.Infrastructure.Persistence;
using Klacks.Api.KnowledgeIndex.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Npgsql;
using Microsoft.Extensions.DependencyInjection;

namespace Klacks.Api.Infrastructure.Extensions;

internal static class RepositoryServiceCollectionExtensions
{
    internal static void AddRepositories(this IServiceCollection services)
    {
        services.AddScoped<IClientRepository, ClientRepository>();
        services.AddScoped<IClientFilterRepository, ClientFilterRepository>();
        services.AddScoped<IClientBreakPlaceholderRepository, ClientBreakPlaceholderRepository>();
        services.AddScoped<IClientSearchRepository, ClientSearchRepository>();
        services.AddScoped<IClientFuzzySearchService, ClientFuzzySearchService>();
        services.AddScoped<IGroupSearchRepository, GroupSearchRepository>();
        services.AddScoped<IShiftSearchRepository, ShiftSearchRepository>();
        services.AddScoped<IClientSearchFilterService, ClientSearchFilterService>();
        services.AddScoped<IClientBaseQueryService, ClientBaseQueryService>();
        services.AddScoped<IAddressRepository, AddressRepository>();
        services.AddScoped<IAnnotationRepository, AnnotationRepository>();
        services.AddScoped<ICommunicationRepository, CommunicationRepository>();
        services.AddScoped<IMembershipRepository, MembershipRepository>();
        services.AddScoped<ISettingsRepository, SettingsRepository>();
        services.AddScoped<ISettingsReader>(sp => sp.GetRequiredService<ISettingsRepository>());
        services.AddScoped<IActiveIndustriesProvider, ActiveIndustriesProvider>();
        services.AddScoped<IAbsenceRepository, AbsenceRepository>();
        services.AddScoped<IBreakPlaceholderRepository, BreakPlaceholderRepository>();
        services.AddScoped<IAbsenceDetailRepository, AbsenceDetailRepository>();
        services.AddScoped<ICountryRepository, CountryRepository>();
        services.AddScoped<IStateRepository, StateRepository>();
        services.AddScoped<ICountryResolver, Klacks.Api.Domain.Services.Common.CountryResolver>();
        services.AddSingleton<Klacks.Api.Domain.Interfaces.Geo.ICountryRegionProvider>(
            _ => Klacks.Api.Infrastructure.Services.Geo.FileCountryRegionProvider.FromBaseDirectory());
        services.AddScoped<Klacks.Api.Domain.Services.Common.StateAbbreviationResolver>();
        services.AddScoped<IBranchRepository, BranchRepository>();
        services.AddScoped<ICalendarSelectionRepository, CalendarSelectionRepository>();
        services.AddScoped<ISelectedCalendarRepository, SelectedCalendarRepository>();
        services.AddScoped<IWorkRepository, WorkRepository>();
        services.AddScoped<IBreakRepository, BreakRepository>();
        services.AddScoped<IWorkChangeRepository, WorkChangeRepository>();
        services.AddScoped<IExpensesRepository, ExpensesRepository>();
        services.AddScoped<IShiftExpensesRepository, ShiftExpensesRepository>();
        services.AddScoped<IScheduleNoteRepository, ScheduleNoteRepository>();
        services.AddScoped<IScheduleCommandRepository, ScheduleCommandRepository>();
        services.AddScoped<IAnalyseScenarioRepository, AnalyseScenarioRepository>();
        services.AddScoped<IWizardRunCaptureRepository, WizardRunCaptureRepository>();
        services.AddScoped<IWizardTrainingRepository, WizardTrainingRepository>();
        services.AddScoped<Klacks.Api.Application.Interfaces.Schedules.IScheduleSnapshotMarkerService,
                           Klacks.Api.Infrastructure.Services.Schedules.ScheduleSnapshotMarkerService>();
        services.AddScoped<IWizardRunCaptureMeasurementService, Klacks.Api.Infrastructure.Services.Schedules.WizardRunCaptureMeasurementService>();
        services.AddScoped<IAnalyseScenarioService, AnalyseScenarioService>();
        services.AddScoped<IShiftRepository, ShiftRepository>();
        services.AddScoped<IShiftGroupScopeReader, Klacks.Api.Infrastructure.Repositories.Schedules.ShiftGroupScopeReadRepository>();
        services.AddScoped<IContainerLockRepository, ContainerLockRepository>();
        services.AddScoped<IContainerWorkChildrenReadRepository, ContainerWorkChildrenReadRepository>();
        services.AddScoped<IGroupRepository, GroupRepository>();
        services.AddScoped<IAssignedGroupRepository, AssignedGroupRepository>();
        services.AddScoped<IGroupItemRepository, GroupItemRepository>();
        services.AddScoped<IClientShiftPreferenceRepository, ClientShiftPreferenceRepository>();
        services.AddScoped<IClientQualificationRepository, ClientQualificationRepository>();
        services.AddScoped<IShiftRequiredQualificationRepository, ShiftRequiredQualificationRepository>();
        services.AddScoped<IQualificationRepository, QualificationRepository>();
        services.AddScoped<IGroupVisibilityRepository, GroupVisibilityRepository>();
        services.AddScoped<IContractRepository, ContractRepository>();
        services.AddScoped<ISchedulingRuleRepository, SchedulingRuleRepository>();
        services.AddScoped<IClientAvailabilityRepository, ClientAvailabilityRepository>();
        services.AddScoped<IClientImageRepository, ClientImageRepository>();
        services.AddScoped<IContainerTemplateRepository, ContainerTemplateRepository>();
        services.AddScoped<IContainerShiftOverrideRepository, ContainerShiftOverrideRepository>();
        services.AddScoped<IIndividualPeriodRepository, IndividualPeriodRepository>();
        services.AddScoped<IMonthlyTargetHoursRepository, MonthlyTargetHoursRepository>();
        services.AddScoped<IPostcodeChRepository, PostcodeChRepository>();
        services.AddScoped<IIdentityProviderRepository, IdentityProviderRepository>();
        services.AddScoped<IIdentityProviderSyncLogRepository, IdentityProviderSyncLogRepository>();
        services.AddScoped<IErpDropPointRepository, ErpDropPointRepository>();
        services.AddScoped<Domain.Interfaces.Imports.IErpImportTokenRepository, Repositories.Imports.ErpImportTokenRepository>();
        services.AddErpObjectStorage();
        services.AddScoped<IPersonalAccessTokenRepository, PersonalAccessTokenRepository>();
        services.AddScoped<IOAuthClientRepository, OAuthClientRepository>();
        services.AddScoped<IOAuthAuthorizationCodeStore,Klacks.Api.Infrastructure.Authentication.OAuthAuthorizationCodeStore>();
        services.AddScoped<IShiftScheduleRepository, ShiftScheduleRepository>();
        services.AddScoped<IReportTemplateRepository, ReportTemplateRepository>();
        services.AddScoped<ILLMRepository, LLMRepository>();
        services.AddScoped<ISkillUsageRepository, SkillUsageRepository>();
        services.AddScoped<IAgentRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AgentRepository>();
        services.AddScoped<IAgentSoulRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AgentSoulRepository>();
        services.AddScoped<IAgentMemoryRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AgentMemoryRepository>();
        services.AddScoped<IPendingUserNoteRepository, Klacks.Api.Infrastructure.Repositories.Assistant.PendingUserNoteRepository>();
        services.AddScoped<IAgentSessionRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AgentSessionRepository>();
        services.AddScoped<IAgentSkillRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AgentSkillRepository>();
        services.AddScoped<IAgentRecipeRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AgentRecipeRepository>();
        services.AddScoped<IScheduledTaskRepository, Klacks.Api.Infrastructure.Repositories.Assistant.ScheduledTaskRepository>();
        services.AddScoped<IScheduledTaskRunner, Klacks.Api.Application.Services.Assistant.Scheduling.ScheduledTaskRunner>();
        services.AddScoped<Klacks.Api.Domain.Interfaces.Assistant.IUnattendedSkillPolicy, Klacks.Api.Application.Services.Assistant.Scheduling.UnattendedSkillPolicy>();
        services.AddScoped<ISkillRelationRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillRelationRepository>();
        services.AddScoped<ISkillPhraseRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillPhraseRepository>();
        services.AddScoped<Klacks.Api.Domain.Interfaces.Assistant.IMemoryRelationRepository, Klacks.Api.Infrastructure.Repositories.Assistant.MemoryRelationRepository>();
        services.AddScoped<INavigationTargetSynonymRepository, Klacks.Api.Infrastructure.Repositories.Assistant.NavigationTargetSynonymRepository>();
        services.AddScoped<IGlobalAgentRuleRepository, Klacks.Api.Infrastructure.Repositories.Assistant.GlobalAgentRuleRepository>();
        services.AddScoped<IUiControlRepository, Klacks.Api.Infrastructure.Repositories.Assistant.UiControlRepository>();
        services.AddScoped<Klacks.Api.Domain.Interfaces.Update.IUpdateHistoryRepository, Klacks.Api.Infrastructure.Repositories.Update.UpdateHistoryRepository>();
        services.AddScoped<Klacks.Api.Domain.Interfaces.Update.IUpdateAvailabilityEvaluator, Klacks.Api.Application.Services.Update.UpdateAvailabilityEvaluator>();
        services.AddScoped<Klacks.Api.Domain.Interfaces.Update.IUpdateManifestReader, Klacks.Api.Infrastructure.Services.Update.UpdateManifestReader>();
        services.AddHttpClient(Klacks.Api.Infrastructure.Services.Update.UpdateManifestReader.HttpClientName);
        services.AddScoped<ISkillLearningClusterRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillLearningClusterRepository>();
        services.AddScoped<ISkillLearningCaseRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillLearningCaseRepository>();
        services.AddScoped<ISkillLearningCandidateRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillLearningCandidateRepository>();
        services.AddScoped<ISkillLearningGoldenCaseRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillLearningGoldenCaseRepository>();
        services.AddScoped<ISkillLearningFitnessRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillLearningFitnessRepository>();
        services.AddScoped<IAnswerGroundingRepository, Klacks.Api.Infrastructure.Repositories.Assistant.AnswerGroundingRepository>();
        services.AddScoped<ISkillSelectionTrajectoryRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillSelectionTrajectoryRepository>();
        services.AddScoped<IEvalRunRepository, Klacks.Api.Infrastructure.Repositories.Assistant.EvalRunRepository>();
        services.AddScoped<IEvalRunItemRepository, Klacks.Api.Infrastructure.Repositories.Assistant.EvalRunItemRepository>();
        services.AddScoped<ISkillEffectivenessRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SkillEffectivenessRepository>();
        services.AddScoped<IProposedSkillChangeRepository, Klacks.Api.Infrastructure.Repositories.Assistant.ProposedSkillChangeRepository>();
        services.AddScoped<ISkillDescriptionOptimizer, Klacks.Api.Application.Services.Assistant.Evaluation.SkillDescriptionOptimizer>();
        services.AddScoped<IReceivedEmailRepository, ReceivedEmailRepository>();
        services.AddScoped<IEmailQueryRepository, EmailQueryRepository>();
        services.AddScoped<IEmailFolderRepository, EmailFolderRepository>();
        services.AddScoped<ISpamRuleRepository, SpamRuleRepository>();
        services.AddScoped<ISentimentKeywordRepository, Klacks.Api.Infrastructure.Repositories.Assistant.SentimentKeywordRepository>();
        services.AddScoped<IPeriodAuditLogRepository, PeriodAuditLogRepository>();
        services.AddScoped<IExportLogRepository, ExportLogRepository>();
        services.AddScoped<IPeriodClosingReadRepository, PeriodClosingReadRepository>();
        services.AddScoped<IResourceMonitorReadRepository, Klacks.Api.Infrastructure.Repositories.Dashboard.ResourceMonitorReadRepository>();
        services.AddScoped<IShiftCoverageReadRepository, Klacks.Api.Infrastructure.Repositories.Dashboard.ShiftCoverageReadRepository>();
        services.AddScoped<ISealedDayRepository, SealedDayRepository>();
        services.AddScoped<IClientSortPreferenceRepository, ClientSortPreferenceRepository>();
        services.AddScoped<Klacks.Api.Domain.Interfaces.Schedules.IScheduleCommandKeywordProvider,
                           Klacks.Api.Infrastructure.Services.Schedules.ScheduleCommandKeywordProvider>();
    }
}
