// Copyright (c) Heribert Gasparoli Private. All rights reserved.

using Klacks.Api.Domain.Enums;

namespace Klacks.Api.Domain.Models.Inbound;

public sealed record ClarificationPolicyFacts(
    bool NeedsClarification,
    EntityTypeEnum ClientType,
    EmailIntent Intent,
    bool FeatureEnabled,
    bool IsAutoGenerated,
    bool HasOpenClarification,
    int QuestionsAskedInRateWindow,
    bool KillSwitchActive,
    AutonomyLevel GlobalAutonomyLevel,
    bool HasPersonalReplyTarget);
