// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Deterministic facts the clarification policy decides on; construct with named arguments only,
/// several adjacent bool parameters describe conditions.
/// </summary>
/// <param name="NeedsClarification">The message requires clarification before routing</param>
/// <param name="ClientType">Entity type of the receiving client</param>
/// <param name="Intent">Classified intent of the inbound email</param>
/// <param name="FeatureEnabled">Clarification feature is enabled for this client</param>
/// <param name="IsAutoGenerated">The email carries auto-reply, bulk, or list headers</param>
/// <param name="HasOpenClarification">The client already has an open clarification pending</param>
/// <param name="QuestionsAskedInRateWindow">Number of questions asked in the rate-limiting window</param>
/// <param name="KillSwitchActive">Global kill switch suppresses all clarification decisions</param>
/// <param name="GlobalAutonomyLevel">Configured autonomy level for the group</param>
/// <param name="HasPersonalReplyTarget">A personal (non-group) reply address was found</param>

using Klacks.Api.Domain.Enums;

namespace Klacks.Api.Domain.Models.Inbound;

public sealed record ClarificationPolicyFacts(
    bool NeedsClarification,
    EntityTypeEnum ClientType,
    EmailIntent Intent,
    bool FeatureEnabled,
    bool IsAutoGenerated,
    bool HasOpenClarification,
    int QuestionsAskedInRateWindow,
    bool KillSwitchActive,
    AutonomyLevel GlobalAutonomyLevel,
    bool HasPersonalReplyTarget);
