// Copyright (c) Heribert Gasparoli Private. All rights reserved.

namespace Klacks.Api.Domain.Models.Inbound;

public sealed record ClarificationEmailThread(
    string MessageId,
    string? InReplyTo,
    string? ThreadReferences,
    bool IsAutoGenerated);
