// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only

namespace Klacks.Api.Domain.Models.Inbound;

public sealed record ClarificationEmailThread(
    string MessageId,
    string? InReplyTo,
    string? ThreadReferences,
    bool IsAutoGenerated);
