// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only

/// <summary>
/// Description texts, in every shipped language, for the seeded calendar rules that are not statutory
/// holidays (is_mandatory = false). Each text states why the day is not an official day off, so the
/// "unofficial" badge in the calendar rule list carries an explanation. Keys follow the lowercase
/// spelling the jsonb description column already stores (zh-cn, zh-tw).
/// </summary>
namespace Klacks.Api.Data.Seed
{
    public static class UnofficialHolidayDescriptionTexts
    {
        public static readonly IReadOnlyDictionary<string, string> EveHalfWorkday = new Dictionary<string, string>
        {
            ["de"] = "Kein gesetzlicher Feiertag; in vielen Betrieben halber Arbeitstag.",
            ["en"] = "Not a public holiday; many businesses work only half a day.",
            ["fr"] = "Pas un jour férié officiel ; dans de nombreuses entreprises, demi-journée de travail.",
            ["it"] = "Non è un giorno festivo ufficiale; in molte aziende si lavora mezza giornata.",
            ["ar"] = "ليس عطلة رسمية؛ كثير من الشركات تعمل نصف يوم فقط.",
            ["cs"] = "Není státní svátek; v mnoha podnicích se pracuje jen půl dne.",
            ["da"] = "Ikke en officiel helligdag; mange virksomheder arbejder kun en halv dag.",
            ["el"] = "Δεν είναι επίσημη αργία· πολλές επιχειρήσεις εργάζονται μόνο μισή ημέρα.",
            ["es"] = "No es festivo oficial; en muchas empresas se trabaja media jornada.",
            ["fi"] = "Ei virallinen vapaapäivä; monessa yrityksessä tehdään vain puolikas työpäivä.",
            ["he"] = "אינו חג רשמי; בעסקים רבים עובדים רק חצי יום.",
            ["id"] = "Bukan hari libur resmi; banyak perusahaan hanya bekerja setengah hari.",
            ["ja"] = "法定の祝日ではありません。多くの企業では半日勤務です。",
            ["ko"] = "법정 공휴일이 아닙니다. 많은 기업에서 반일만 근무합니다.",
            ["ms"] = "Bukan cuti umum rasmi; banyak syarikat hanya bekerja separuh hari.",
            ["nb"] = "Ikke en offisiell helligdag; mange bedrifter har bare halv arbeidsdag.",
            ["nl"] = "Geen officiële feestdag; in veel bedrijven wordt maar een halve dag gewerkt.",
            ["pl"] = "Nie jest dniem ustawowo wolnym; w wielu firmach pracuje się tylko pół dnia.",
            ["pt"] = "Não é feriado oficial; em muitas empresas trabalha-se apenas meio dia.",
            ["ro"] = "Nu este sărbătoare legală; în multe firme se lucrează doar jumătate de zi.",
            ["sv"] = "Ingen allmän helgdag; många företag arbetar bara halva dagen.",
            ["th"] = "ไม่ใช่วันหยุดตามกฎหมาย หลายบริษัททำงานเพียงครึ่งวัน",
            ["vi"] = "Không phải ngày lễ chính thức; nhiều doanh nghiệp chỉ làm việc nửa ngày.",
            ["zh-cn"] = "非法定节假日；许多企业只上半天班。",
            ["zh-tw"] = "非法定假日；許多企業只上半天班。",
        };

        public static readonly IReadOnlyDictionary<string, string> EveNormalWorkday = new Dictionary<string, string>
        {
            ["de"] = "Kein gesetzlicher Feiertag; normaler Arbeitstag, sofern Betrieb oder Arbeitsvertrag nichts anderes vorsehen.",
            ["en"] = "Not a public holiday; a normal working day unless the company or the employment contract provides otherwise.",
            ["fr"] = "Pas un jour férié officiel ; jour ouvrable normal, sauf disposition contraire de l'entreprise ou du contrat de travail.",
            ["it"] = "Non è un giorno festivo ufficiale; normale giornata lavorativa, salvo diversa disposizione dell'azienda o del contratto di lavoro.",
            ["ar"] = "ليس عطلة رسمية؛ يوم عمل عادي ما لم تنص الشركة أو عقد العمل على خلاف ذلك.",
            ["cs"] = "Není státní svátek; běžný pracovní den, pokud podnik nebo pracovní smlouva nestanoví jinak.",
            ["da"] = "Ikke en officiel helligdag; almindelig arbejdsdag, medmindre virksomheden eller ansættelseskontrakten bestemmer andet.",
            ["el"] = "Δεν είναι επίσημη αργία· κανονική εργάσιμη ημέρα, εκτός αν η επιχείρηση ή η σύμβαση εργασίας ορίζει διαφορετικά.",
            ["es"] = "No es festivo oficial; día laborable normal, salvo que la empresa o el contrato de trabajo dispongan otra cosa.",
            ["fi"] = "Ei virallinen vapaapäivä; tavallinen työpäivä, ellei yritys tai työsopimus toisin määrää.",
            ["he"] = "אינו חג רשמי; יום עבודה רגיל, אלא אם החברה או חוזה העבודה קובעים אחרת.",
            ["id"] = "Bukan hari libur resmi; hari kerja biasa kecuali perusahaan atau kontrak kerja menetapkan lain.",
            ["ja"] = "法定の祝日ではありません。会社または雇用契約に別段の定めがない限り、通常の勤務日です。",
            ["ko"] = "법정 공휴일이 아닙니다. 회사나 근로계약에서 달리 정하지 않는 한 평상 근무일입니다.",
            ["ms"] = "Bukan cuti umum rasmi; hari bekerja biasa kecuali syarikat atau kontrak pekerjaan menetapkan sebaliknya.",
            ["nb"] = "Ikke en offisiell helligdag; vanlig arbeidsdag med mindre bedriften eller arbeidsavtalen bestemmer noe annet.",
            ["nl"] = "Geen officiële feestdag; een gewone werkdag, tenzij het bedrijf of de arbeidsovereenkomst anders bepaalt.",
            ["pl"] = "Nie jest dniem ustawowo wolnym; zwykły dzień roboczy, chyba że firma lub umowa o pracę stanowi inaczej.",
            ["pt"] = "Não é feriado oficial; dia útil normal, salvo disposição diferente da empresa ou do contrato de trabalho.",
            ["ro"] = "Nu este sărbătoare legală; zi lucrătoare obișnuită, dacă firma sau contractul de muncă nu prevăd altfel.",
            ["sv"] = "Ingen allmän helgdag; vanlig arbetsdag om inte företaget eller anställningsavtalet föreskriver annat.",
            ["th"] = "ไม่ใช่วันหยุดตามกฎหมาย เป็นวันทำงานปกติ เว้นแต่บริษัทหรือสัญญาจ้างจะกำหนดไว้เป็นอย่างอื่น",
            ["vi"] = "Không phải ngày lễ chính thức; là ngày làm việc bình thường, trừ khi doanh nghiệp hoặc hợp đồng lao động quy định khác.",
            ["zh-cn"] = "非法定节假日；除非企业或劳动合同另有规定，否则为正常工作日。",
            ["zh-tw"] = "非法定假日；除非企業或勞動契約另有規定，否則為正常工作日。",
        };

        public static readonly IReadOnlyDictionary<string, string> AlwaysOnSunday = new Dictionary<string, string>
        {
            ["de"] = "Fällt immer auf einen Sonntag; kein zusätzlicher arbeitsfreier Tag.",
            ["en"] = "Always falls on a Sunday; no additional day off.",
            ["fr"] = "Tombe toujours un dimanche ; pas de jour de congé supplémentaire.",
            ["it"] = "Cade sempre di domenica; nessun giorno libero aggiuntivo.",
            ["ar"] = "يصادف دائمًا يوم أحد؛ لا يوجد يوم عطلة إضافي.",
            ["cs"] = "Připadá vždy na neděli; žádný další den volna.",
            ["da"] = "Falder altid på en søndag; ingen ekstra fridag.",
            ["el"] = "Πέφτει πάντα Κυριακή· δεν υπάρχει επιπλέον ημέρα αργίας.",
            ["es"] = "Siempre cae en domingo; no hay día libre adicional.",
            ["fi"] = "Osuu aina sunnuntaille; ei ylimääräistä vapaapäivää.",
            ["he"] = "חל תמיד ביום ראשון; אין יום חופש נוסף.",
            ["id"] = "Selalu jatuh pada hari Minggu; tidak ada hari libur tambahan.",
            ["ja"] = "常に日曜日にあたるため、追加の休日はありません。",
            ["ko"] = "항상 일요일에 해당하므로 추가 휴일은 없습니다.",
            ["ms"] = "Sentiasa jatuh pada hari Ahad; tiada hari cuti tambahan.",
            ["nb"] = "Faller alltid på en søndag; ingen ekstra fridag.",
            ["nl"] = "Valt altijd op een zondag; geen extra vrije dag.",
            ["pl"] = "Zawsze przypada w niedzielę; brak dodatkowego dnia wolnego.",
            ["pt"] = "Cai sempre num domingo; não há dia de folga adicional.",
            ["ro"] = "Cade întotdeauna duminica; nu există o zi liberă suplimentară.",
            ["sv"] = "Infaller alltid på en söndag; ingen extra ledig dag.",
            ["th"] = "ตรงกับวันอาทิตย์เสมอ จึงไม่มีวันหยุดเพิ่มเติม",
            ["vi"] = "Luôn rơi vào Chủ nhật; không có ngày nghỉ bổ sung.",
            ["zh-cn"] = "总是在星期日；不额外放假。",
            ["zh-tw"] = "總是在星期日；不另外放假。",
        };

        public static readonly IReadOnlyDictionary<string, string> SomeMunicipalitiesOnly = new Dictionary<string, string>
        {
            ["de"] = "Kein kantonaler Feiertag; nur in einzelnen Gemeinden gesetzlicher Feiertag.",
            ["en"] = "Not a cantonal public holiday; an official holiday only in some municipalities.",
            ["fr"] = "Pas un jour férié cantonal ; férié officiel seulement dans certaines communes.",
            ["it"] = "Non è un giorno festivo cantonale; festivo ufficiale solo in alcuni comuni.",
            ["ar"] = "ليس عطلة رسمية على مستوى الكانتون؛ عطلة رسمية في بعض البلديات فقط.",
            ["cs"] = "Není kantonální svátek; úředním svátkem je jen v některých obcích.",
            ["da"] = "Ikke en kantonal helligdag; kun officiel helligdag i enkelte kommuner.",
            ["el"] = "Δεν είναι αργία σε επίπεδο καντονιού· επίσημη αργία μόνο σε ορισμένους δήμους.",
            ["es"] = "No es festivo cantonal; solo es festivo oficial en algunos municipios.",
            ["fi"] = "Ei kantonin virallinen vapaapäivä; virallinen vapaapäivä vain joissakin kunnissa.",
            ["he"] = "אינו חג רשמי ברמת הקנטון; חג רשמי רק בחלק מהרשויות המקומיות.",
            ["id"] = "Bukan hari libur resmi kanton; hari libur resmi hanya di beberapa kotamadya.",
            ["ja"] = "州の祝日ではなく、一部の市町村でのみ法定の祝日です。",
            ["ko"] = "칸톤 공휴일이 아니며, 일부 지방자치단체에서만 법정 공휴일입니다.",
            ["ms"] = "Bukan cuti umum kanton; cuti rasmi hanya di sesetengah majlis perbandaran.",
            ["nb"] = "Ikke en kantonal helligdag; offisiell helligdag bare i enkelte kommuner.",
            ["nl"] = "Geen kantonale feestdag; alleen in sommige gemeenten een officiële feestdag.",
            ["pl"] = "Nie jest świętem kantonalnym; dniem ustawowo wolnym tylko w niektórych gminach.",
            ["pt"] = "Não é feriado cantonal; é feriado oficial apenas em alguns municípios.",
            ["ro"] = "Nu este sărbătoare cantonală; sărbătoare legală doar în unele comune.",
            ["sv"] = "Ingen kantonal helgdag; officiell helgdag endast i vissa kommuner.",
            ["th"] = "ไม่ใช่วันหยุดระดับแคนตัน เป็นวันหยุดตามกฎหมายเฉพาะในบางเทศบาล",
            ["vi"] = "Không phải ngày lễ của bang; chỉ là ngày lễ chính thức ở một số xã.",
            ["zh-cn"] = "非州级法定节假日；仅在部分市镇为法定节假日。",
            ["zh-tw"] = "非州級法定假日；僅在部分市鎮為法定假日。",
        };

        public static readonly IReadOnlyDictionary<string, string> AustrianGoodFriday = new Dictionary<string, string>
        {
            ["de"] = "Seit 2019 kein gesetzlicher Feiertag mehr; Arbeitnehmende können einen Urlaubstag pro Jahr als persönlichen Feiertag festlegen.",
            ["en"] = "No longer a public holiday since 2019; employees may designate one day of annual leave per year as a personal holiday.",
            ["fr"] = "N'est plus un jour férié officiel depuis 2019 ; les salariés peuvent désigner chaque année un jour de congé comme jour férié personnel.",
            ["it"] = "Dal 2019 non è più un giorno festivo ufficiale; i dipendenti possono indicare ogni anno un giorno di ferie come festività personale.",
            ["ar"] = "لم يعد عطلة رسمية منذ عام 2019؛ يجوز للموظفين تحديد يوم واحد من الإجازة السنوية كل عام كعطلة شخصية.",
            ["cs"] = "Od roku 2019 již není státním svátkem; zaměstnanci si mohou jeden den dovolené ročně určit jako osobní svátek.",
            ["da"] = "Siden 2019 ikke længere en officiel helligdag; medarbejdere kan hvert år udpege én feriedag som personlig helligdag.",
            ["el"] = "Από το 2019 δεν είναι πλέον επίσημη αργία· οι εργαζόμενοι μπορούν να ορίσουν μία ημέρα άδειας τον χρόνο ως προσωπική αργία.",
            ["es"] = "Desde 2019 ya no es festivo oficial; los empleados pueden designar un día de vacaciones al año como festivo personal.",
            ["fi"] = "Ei ole ollut virallinen vapaapäivä vuoden 2019 jälkeen; työntekijä voi nimetä vuosittain yhden lomapäivän henkilökohtaiseksi vapaapäiväksi.",
            ["he"] = "אינו עוד חג רשמי מאז 2019; עובדים רשאים לקבוע יום חופשה אחד בשנה כחג אישי.",
            ["id"] = "Sejak 2019 bukan lagi hari libur resmi; karyawan dapat menetapkan satu hari cuti tahunan setiap tahun sebagai hari libur pribadi.",
            ["ja"] = "2019年以降は法定の祝日ではありません。従業員は年に1日、年次休暇を個人の祝日として指定できます。",
            ["ko"] = "2019년부터 더 이상 법정 공휴일이 아닙니다. 직원은 매년 연차 휴가 중 하루를 개인 공휴일로 지정할 수 있습니다.",
            ["ms"] = "Bukan lagi cuti umum rasmi sejak 2019; pekerja boleh menetapkan satu hari cuti tahunan setiap tahun sebagai cuti peribadi.",
            ["nb"] = "Ikke lenger en offisiell helligdag siden 2019; arbeidstakere kan hvert år velge én feriedag som personlig helligdag.",
            ["nl"] = "Sinds 2019 geen officiële feestdag meer; werknemers kunnen per jaar één vakantiedag als persoonlijke feestdag aanwijzen.",
            ["pl"] = "Od 2019 roku nie jest już dniem ustawowo wolnym; pracownicy mogą co roku wyznaczyć jeden dzień urlopu jako osobiste święto.",
            ["pt"] = "Desde 2019 deixou de ser feriado oficial; os trabalhadores podem designar um dia de férias por ano como feriado pessoal.",
            ["ro"] = "Din 2019 nu mai este sărbătoare legală; angajații pot desemna anual o zi de concediu drept sărbătoare personală.",
            ["sv"] = "Sedan 2019 inte längre en allmän helgdag; anställda kan varje år välja en semesterdag som personlig helgdag.",
            ["th"] = "ไม่ใช่วันหยุดตามกฎหมายอีกต่อไปตั้งแต่ปี 2019 พนักงานสามารถกำหนดวันลาพักร้อนหนึ่งวันต่อปีเป็นวันหยุดส่วนตัวได้",
            ["vi"] = "Không còn là ngày lễ chính thức từ năm 2019; người lao động có thể chọn mỗi năm một ngày phép năm làm ngày lễ cá nhân.",
            ["zh-cn"] = "自2019年起不再是法定节假日；员工每年可将一天年假指定为个人假日。",
            ["zh-tw"] = "自2019年起不再是法定假日；員工每年可將一天年假指定為個人假日。",
        };

        public static readonly IReadOnlyDictionary<string, string> RegionalHoliday = new Dictionary<string, string>
        {
            ["de"] = "Regionaler Feiertag: meist schulfrei und in der öffentlichen Verwaltung arbeitsfrei, aber kein gesetzlicher Feiertag für private Arbeitgeber.",
            ["en"] = "Regional holiday: schools and public administration are usually closed, but it is not a statutory holiday for private employers.",
            ["fr"] = "Fête régionale : écoles et administrations publiques généralement fermées, mais pas un jour férié légal pour les employeurs privés.",
            ["it"] = "Festa regionale: di solito scuole e pubblica amministrazione sono chiuse, ma non è un giorno festivo per legge per i datori di lavoro privati.",
            ["ar"] = "عطلة إقليمية: تُغلق المدارس والإدارات العامة عادةً، لكنها ليست عطلة قانونية لأصحاب العمل في القطاع الخاص.",
            ["cs"] = "Regionální svátek: školy a veřejná správa jsou obvykle zavřené, pro soukromé zaměstnavatele však nejde o zákonný svátek.",
            ["da"] = "Regional helligdag: skoler og offentlig forvaltning holder normalt lukket, men det er ikke en lovbestemt helligdag for private arbejdsgivere.",
            ["el"] = "Περιφερειακή αργία: τα σχολεία και η δημόσια διοίκηση συνήθως κλείνουν, αλλά δεν είναι νόμιμη αργία για τους ιδιώτες εργοδότες.",
            ["es"] = "Festivo regional: escuelas y administración pública suelen cerrar, pero no es festivo legal para los empleadores privados.",
            ["fi"] = "Alueellinen juhlapäivä: koulut ja julkishallinto ovat yleensä kiinni, mutta se ei ole lakisääteinen vapaapäivä yksityisille työnantajille.",
            ["he"] = "חג אזורי: בתי הספר והמינהל הציבורי בדרך כלל סגורים, אך אין זה חג חוקי למעסיקים פרטיים.",
            ["id"] = "Hari libur daerah: sekolah dan administrasi publik biasanya tutup, tetapi bukan hari libur resmi menurut undang-undang bagi pemberi kerja swasta.",
            ["ja"] = "地域の祝日です。学校や官公庁は通常休みですが、民間の雇用主にとっては法定の祝日ではありません。",
            ["ko"] = "지역 기념일입니다. 학교와 공공 행정기관은 보통 쉬지만, 민간 고용주에게는 법정 공휴일이 아닙니다.",
            ["ms"] = "Cuti wilayah: sekolah dan pentadbiran awam biasanya ditutup, tetapi ia bukan cuti berkanun bagi majikan swasta.",
            ["nb"] = "Regional helligdag: skoler og offentlig forvaltning holder vanligvis stengt, men det er ingen lovbestemt helligdag for private arbeidsgivere.",
            ["nl"] = "Regionale feestdag: scholen en overheidsdiensten zijn meestal gesloten, maar het is geen wettelijke feestdag voor particuliere werkgevers.",
            ["pl"] = "Święto regionalne: szkoły i administracja publiczna są zwykle zamknięte, ale nie jest to dzień ustawowo wolny u prywatnych pracodawców.",
            ["pt"] = "Feriado regional: escolas e administração pública costumam fechar, mas não é feriado legal para empregadores privados.",
            ["ro"] = "Sărbătoare regională: școlile și administrația publică sunt de obicei închise, dar nu este sărbătoare legală pentru angajatorii privați.",
            ["sv"] = "Regional helgdag: skolor och offentlig förvaltning har vanligtvis stängt, men det är ingen lagstadgad helgdag för privata arbetsgivare.",
            ["th"] = "วันหยุดระดับภูมิภาค โรงเรียนและหน่วยงานราชการมักปิด แต่ไม่ใช่วันหยุดตามกฎหมายสำหรับนายจ้างเอกชน",
            ["vi"] = "Ngày lễ địa phương: trường học và cơ quan hành chính công thường nghỉ, nhưng không phải ngày lễ theo luật đối với người sử dụng lao động tư nhân.",
            ["zh-cn"] = "地区性节日：学校和公共行政机构通常放假，但对私营雇主而言并非法定节假日。",
            ["zh-tw"] = "地區性節日：學校與公共行政機關通常放假，但對私人雇主而言並非法定假日。",
        };

        public static readonly IReadOnlyDictionary<string, string> UsFederalHoliday = new Dictionary<string, string>
        {
            ["de"] = "Bundesfeiertag für Bundesbehörden; private Arbeitgeber sind gesetzlich nicht verpflichtet, freizugeben.",
            ["en"] = "Federal holiday for federal agencies; private employers are not legally required to give the day off.",
            ["fr"] = "Jour férié fédéral pour les administrations fédérales ; les employeurs privés ne sont pas légalement tenus d'accorder congé.",
            ["it"] = "Festività federale per gli enti federali; i datori di lavoro privati non sono obbligati per legge a concedere il giorno libero.",
            ["ar"] = "عطلة اتحادية للجهات الحكومية الاتحادية؛ أصحاب العمل في القطاع الخاص غير ملزمين قانونًا بمنح يوم عطلة.",
            ["cs"] = "Federální svátek pro federální úřady; soukromí zaměstnavatelé nejsou ze zákona povinni poskytnout volno.",
            ["da"] = "Føderal helligdag for føderale myndigheder; private arbejdsgivere er ikke ved lov forpligtet til at give fri.",
            ["el"] = "Ομοσπονδιακή αργία για τις ομοσπονδιακές υπηρεσίες· οι ιδιώτες εργοδότες δεν υποχρεούνται από τον νόμο να δώσουν ρεπό.",
            ["es"] = "Festivo federal para las agencias federales; los empleadores privados no están obligados por ley a dar el día libre.",
            ["fi"] = "Liittovaltion vapaapäivä liittovaltion virastoille; yksityiset työnantajat eivät ole lain mukaan velvollisia antamaan vapaata.",
            ["he"] = "חג פדרלי לרשויות הפדרליות; מעסיקים פרטיים אינם מחויבים על פי חוק לתת יום חופש.",
            ["id"] = "Hari libur federal bagi instansi federal; pemberi kerja swasta tidak diwajibkan oleh hukum untuk memberikan hari libur.",
            ["ja"] = "連邦政府機関の祝日です。民間の雇用主には休日を与える法的義務はありません。",
            ["ko"] = "연방 기관의 연방 공휴일입니다. 민간 고용주는 법적으로 휴무를 줄 의무가 없습니다.",
            ["ms"] = "Cuti persekutuan bagi agensi persekutuan; majikan swasta tidak diwajibkan oleh undang-undang untuk memberi cuti.",
            ["nb"] = "Føderal helligdag for føderale etater; private arbeidsgivere er ikke lovpålagt å gi fri.",
            ["nl"] = "Federale feestdag voor federale instanties; particuliere werkgevers zijn wettelijk niet verplicht vrij te geven.",
            ["pl"] = "Święto federalne dla urzędów federalnych; prywatni pracodawcy nie mają ustawowego obowiązku udzielania dnia wolnego.",
            ["pt"] = "Feriado federal para os órgãos federais; os empregadores privados não são legalmente obrigados a dar folga.",
            ["ro"] = "Sărbătoare federală pentru instituțiile federale; angajatorii privați nu sunt obligați prin lege să acorde zi liberă.",
            ["sv"] = "Federal helgdag för federala myndigheter; privata arbetsgivare är inte skyldiga enligt lag att ge ledigt.",
            ["th"] = "วันหยุดของหน่วยงานรัฐบาลกลาง นายจ้างเอกชนไม่มีหน้าที่ตามกฎหมายต้องให้หยุดงาน",
            ["vi"] = "Ngày lễ liên bang dành cho các cơ quan liên bang; người sử dụng lao động tư nhân không bắt buộc theo luật phải cho nghỉ.",
            ["zh-cn"] = "联邦机构的联邦假日；私营雇主在法律上没有义务放假。",
            ["zh-tw"] = "聯邦機關的聯邦假日；私人雇主在法律上沒有義務放假。",
        };
    }
}
