// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Tells whether a received mail was generated automatically (auto-reply, out-of-office notice,
/// mailing-list or bulk mail) from its headers: Auto-Submitted with any value other than "no"
/// (RFC 3834), Precedence bulk/list/junk, a List-Id header, or the de-facto auto-responder headers
/// X-Autoreply and X-Autorespond. The inbound clarification dialog never asks back on such a mail,
/// which together with the rate limit prevents mail loops between Klacksy and an auto-responder.
/// </summary>
/// <param name="headers">Header list of the parsed MIME message</param>

using MimeKit;

namespace Klacks.Api.Infrastructure.Email;

internal static class EmailAutoGeneratedDetector
{
    private const string AutoSubmittedHeader = "Auto-Submitted";
    private const string AutoSubmittedNoValue = "no";
    private const string PrecedenceHeader = "Precedence";
    private const string ListIdHeader = "List-Id";
    private const string XAutoreplyHeader = "X-Autoreply";
    private const string XAutorespondHeader = "X-Autorespond";
    private const char HeaderParameterSeparator = ';';

    private static readonly string[] BulkPrecedenceValues = ["bulk", "list", "junk"];

    internal static bool IsAutoGenerated(HeaderList headers)
    {
        var autoSubmitted = headers[AutoSubmittedHeader];
        if (!string.IsNullOrWhiteSpace(autoSubmitted))
        {
            var token = autoSubmitted.Split(HeaderParameterSeparator)[0].Trim();
            if (!string.Equals(token, AutoSubmittedNoValue, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        var precedence = headers[PrecedenceHeader]?.Trim();
        if (!string.IsNullOrEmpty(precedence)
            && BulkPrecedenceValues.Contains(precedence, StringComparer.OrdinalIgnoreCase))
        {
            return true;
        }

        return headers.Contains(ListIdHeader)
               || headers.Contains(XAutoreplyHeader)
               || headers.Contains(XAutorespondHeader);
    }
}
