// Copyright (c) Heribert Gasparoli Private. All rights reserved.

namespace Klacks.Api.Domain.Enums;

public enum ClarificationSkipReason
{
    NotNeeded = 0,
    NotEmployee = 1,
    NotPlanningRelevant = 2,
    FeatureDisabled = 3,
    AutoGeneratedEmail = 4,
    OpenClarificationExists = 5,
    RateLimited = 6,
    NoPersonalReplyTarget = 7
}
